name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: KEXT
  EXCLUDED_ARCHS: arm64e

jobs:
  build:
    name: Build
    runs-on: macos-13
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: acidanthera/MacKernelSDK
          path: MacKernelSDK
      - name: CI Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/ocbuild/refs/heads/master/ci-bootstrap.sh) && eval "$src" || exit 1
      - name: Lilu Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/refs/heads/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1
      - name: AsusSMC Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/yjmd2222/AsusSMC/refs/heads/master/Scripts/bootstrap.sh) && eval "$src" || exit 1
      - run: xcodebuild -jobs 1 -configuration Debug
      - run: xcodebuild -jobs 1 -configuration Release

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/*/*.zip
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*/*.zip
          tag: ${{ github.ref }}
          file_glob: true

  analyze-clang:
    name: Analyze Clang
    runs-on: macos-13
    env:
      JOB_TYPE: ANALYZE
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: acidanthera/MacKernelSDK
          path: MacKernelSDK
      - name: CI Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/ocbuild/refs/heads/master/ci-bootstrap.sh) && eval "$src" || exit 1
      - name: Lilu Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/refs/heads/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1
      - name: AsusSMC Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/yjmd2222/AsusSMC/refs/heads/master/Scripts/bootstrap.sh) && eval "$src" || exit 1
      - run: xcodebuild analyze -quiet -scheme AsusSMC -configuration Debug CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze" && [ "$(find clang-analyze -name "*.html")" = "" ]
      - run: xcodebuild analyze -quiet -scheme AsusSMC -configuration Release CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze" && [ "$(find clang-analyze -name "*.html")" = "" ]

